<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b32c8b49-3009-4e7a-8009-cec4a3f2cb12</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.19.24" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.11" />
    <PackageReference Include="Sentry.AspNetCore" Version="6.9.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgizDisSaglikTakip.Business\AgizDisSaglikTakip.Business.csproj" />
    <ProjectReference Include="..\AgizDisSaglikTakip.Core\AgizDisSaglikTakip.Core.csproj" />
    <ProjectReference Include="..\AgizDisSaglikTakip.DataAccess\AgizDisSaglikTakip.DataAccess.csproj" />
  </ItemGroup>

</Project>
