<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AgizDisSaglikTakip.Entities\AgizDisSaglikTakip.Entities.csproj" />
    <ProjectReference Include="..\AgizDisSaglikTakip.Core\AgizDisSaglikTakip.Core.csproj" />
    <ProjectReference Include="..\AgizDisSaglikTakip.DataAccess\AgizDisSaglikTakip.DataAccess.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
