// <auto-generated />
using System;
using AgizDisSaglikTakip.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgizDisSaglikTakip.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816121111_AddTrackingTypeAndMakeDurationNullable")]
    partial class AddTrackingTypeAndMakeDurationNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgizDisSaglikTakip.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("AgizDisSaglikTakip.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.Property<int>("PeriodFrequency")
                        .HasColumnType("int");

                    b.Property<int>("PeriodUnit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TrackingType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("AgizDisSaglikTakip.Entities.GoalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ActivityDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ActivityTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalStatuses");
                });

            modelBuilder.Entity("AgizDisSaglikTakip.Entities.StatusNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StatusNotes");
                });

            modelBuilder.Entity("AgizDisSaglikTakip.Entities.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Suggestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Dişlerinizi günde en az iki kez, sabah ve akşam fırçalayın."
                        },
                        new
                        {
                            Id = 2,
                            Text = "Diş ipini her gün kullanarak diş aralarındaki plağı temizleyin."
                        },
                        new
                        {
                            Id = 3,
                            Text = "Şekerli ve asitli içecekleri azaltarak dişlerinizi çürükten koruyun."
                        },
                        new
                        {
                            Id = 4,
                            Text = "Diş fırçanızı her 3 ayda bir, kılları yıprandığında yenileyin."
                        },
                        new
                        {
                            Id = 5,
                            Text = "Ağız gargarası kullanarak ağız kokusunu ve bakteri oluşumunu azaltabilirsiniz."
                        },
                        new
                        {
                            Id = 6,
                            Text = "Diş hekiminizi yılda en az iki kez düzenli kontrol için ziyaret edin."
                        },
                        new
                        {
                            Id = 7,
                            Text = "Sert kıllı yerine yumuşak kıllı diş fırçası tercih edin."
                        },
                        new
                        {
                            Id = 8,
                            Text = "Asitli gıdalardan sonra dişlerinizi hemen değil, 30 dakika bekleyip fırçalayın."
                        },
                        new
                        {
                            Id = 9,
                            Text = "Bol su içerek ağzınızın kurumasını önleyin, tükürük diş sağlığını korur."
                        },
                        new
                        {
                            Id = 10,
                            Text = "Tırnak yeme ve kalem çiğneme gibi alışkanlıklardan kaçının, dişlerinize zarar verir."
                        });
                });

            modelBuilder.Entity("AgizDisSaglikTakip.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordEncrypted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("PasswordResetCodeExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AgizDisSaglikTakip.Entities.Goal", b =>
                {
                    b.HasOne("AgizDisSaglikTakip.Entities.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgizDisSaglikTakip.Entities.GoalStatus", b =>
                {
                    b.HasOne("AgizDisSaglikTakip.Entities.Goal", "Goal")
                        .WithMany("GoalStatuses")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("AgizDisSaglikTakip.Entities.StatusNote", b =>
                {
                    b.HasOne("AgizDisSaglikTakip.Entities.User", "User")
                        .WithMany("StatusNotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgizDisSaglikTakip.Entities.Goal", b =>
                {
                    b.Navigation("GoalStatuses");
                });

            modelBuilder.Entity("AgizDisSaglikTakip.Entities.User", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("StatusNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
